#pragma once

enum OBJID {  UI_DOOR, PLAYER, MONSTER, BOSS, MONSTER_BULLET, ITEM, MOUSE,HP, UI, UI_BUTTON,  OBJ_END };

enum Scene { MENU, STAGE1, STAGE2, BOSS_STAGE1, BOSS_STAGE2 , EDIT, SCENE_END };